# Generated by Django 5.1.7 on 2025-03-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sosconfig",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="sosconfig",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="sosconfig",
            name="emergency_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="sosconfig",
            name="sos_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
