# Generated by Django 5.1.7 on 2025-03-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0002_remove_sosconfig_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sosconfig",
            old_name="sos_enabled",
            new_name="battery_sos_enabled",
        ),
        migrations.RenameField(
            model_name="sosconfig",
            old_name="elderly",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="sosconfig",
            name="battery_alert",
        ),
        migrations.RemoveField(
            model_name="sosconfig",
            name="emergency_number",
        ),
        migrations.RemoveField(
            model_name="sosconfig",
            name="fall_threshold",
        ),
        migrations.AddField(
            model_name="sosconfig",
            name="battery_threshold",
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name="sosconfig",
            name="cctv_fall_sos_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sosconfig",
            name="contact_mode",
            field=models.CharField(
                choices=[("text", "Text"), ("call", "Call")],
                default="text",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="sosconfig",
            name="phone_fall_sos_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
